### PR TITLE
Remotes/origin/dev improve crosscompilation v3

### PR DESCRIPTION
**Pull request by zinosat**
This is the newer version of the patch, which leaves the "NATIVE" variable unchanged and stores the target architecture in the "MACHINE" variable

### CODE REVIEW

**Comment by cardigliano** [comment]
@zinosat please update you branch to exclude userland/examples_ft/ftflow_dpdk.c from your patch.  Please also see my comments inline. Thank you.

**Comment by zinosat** [comment]
> @zinosat please update you branch to exclude userland/examples_ft/ftflow_dpdk.c from your patch. Please also see my comments inline. Thank you.

Hi Alfredo,
I can't see your comments inline and I don't understand why my patch gets mixed with  userland/examples_ft/ftflow_dpdk.c: maybe I need to create the branch from a previous commit rather than from the tip of "dev"?

**Comment by cardigliano** [comment]
@zinosat this is my comment about "MACHINE": "I realized this generates x86-64 instead of x86_64 on x86, leading to errors linking libraries from libs/lib*$MACHINE*. Could you explain where is this actually needed?"

**Comment by zinosat** [comment]
> @zinosat this is my comment about "MACHINE": "I realized this generates x86-64 instead of x86_64 on x86, leading to errors linking libraries from libs/lib*$MACHINE*. Could you explain where is this actually needed?"

I've noticed that 

$CC -dumpmachine | cut -d '-' -f 1

gives me x86_64 on my x86 laptop and  "arm" when crosscompiling, which seems to fit your needs.
When I crosscompile, I use this:
...
        cd $(@D)/userland; autoreconf -ivf ; \
                $(TARGET_MAKE_ENV) ./configure \
                --host=$(GNU_HOST_NAME) \
                --disable-bpf \
                $(TARGET_CONFIGURE_OPTS)
...
        $(TARGET_MAKE_ENV) $(MAKE1) \
                AR="$(TARGET_AR)" CC="$(TARGET_CC)" RANLIB="$(TARGET_RANLIB)" \
                -C $(@D)/userland/lib

so, what I basically need, is to be able to set variables like CC/AR/RANLIB which aren't necessarely the same which you use in a native environment

**Comment by zinosat** [comment]
I've created a new branch dev-improve-crosscompilation-v4 which is started from 77c196e93aed56518b78d94e46c0e3fe18d33aa7 rather than from the latest commit of "dev".

MACHINE is now obtained via "$CC -dumpmachine | cut -d '-' -f 1"

I've also amended the commit message which should now give all the necessary details 

let me know if it's fine to create a new pull request

regards,
Davide

**Comment by cardigliano** [comment]
@zinosat yes please send a new pull request. Thank you.

**Pull request closed without merging**
